export const api = {
  AuthAppsLogin: '/api/auth/login',
  User: '/api/users/users',
  UsersCreate: '/api/users',
  UserUpdate: '/api/users/user',
  Users: '/users',
  ProfileImage: '/api/profile_image',
  CartItems: '/api/cart_items',
  FoodReview: '/api/food_item_reviews',
  FoodItem: '/api/food_items',
  OrderStatuses: '/api/order_statuses',
  Orders: '/api/orders',
  OrderItems: '/api/order_items',
  StatusHistory: '/api/order_status_history',
  PushNotification: '/api/push_notification',
};
